# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Psalm static analysis

on:
  pull_request:
    paths:
      - .github/workflows/psalm.yml
      - appinfo/**
      - composer.*
      - lib/**
      - templates/**
      - tests/**
  push:
    branches:
      - main
      - stable*
      - test
    paths:
      - .github/workflows/psalm.yml
      - appinfo/**
      - composer.*
      - lib/**
      - templates/**
      - tests/**

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    strategy:
      # do not stop on another job's failure
      fail-fast: false
      matrix:
        ocp-version: ['30', '31', '32', 'dev-master']
        php-version: ['8.2', '8.3', '8.4']


    name: Psalm, PHP ${{ matrix.php-version }}, OCP ${{ matrix.ocp-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up php
        uses: shivammathur/setup-php@7fdd3ece872ec7ec4c098ae5ab7637d5e0a96067 # v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          ini-file: development
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: |
          composer remove --dev phpunit/phpunit
          composer i

      - name: Install dependencies
        run: composer require --dev nextcloud/ocp:${{ matrix.ocp-version }} --ignore-platform-reqs --with-dependencies

      - name: Install dependencies
        run: composer require --dev

      - name: Run coding standards check
        run: composer run psalm

  summary:
    runs-on: ubuntu-latest
    needs: static-analysis

    if: always()

    name: static-psalm-analysis-summary

    steps:
      - name: Summary status
        run: if ${{ needs.static-analysis.result != 'success' }}; then exit 1; fi
